import Link from "next/link";
import { SiteNav } from "@/app/components/site-nav";
import { SiteFooter } from "@/app/components/site-footer";
import { Portrait } from "@/app/components/portrait";
import { packages, styleCategories, stats } from "@/lib/data";

const steps = [
  {
    n: "01",
    title: "Upload selfies",
    body: "Drop 10–25 photos. We validate faces, resolution and blur automatically.",
  },
  {
    n: "02",
    title: "Train your model",
    body: "We build a private identity model that captures exactly how you look.",
  },
  {
    n: "03",
    title: "Generate styles",
    body: "Pick from 120+ professional scenarios. We render and rank the best.",
  },
  {
    n: "04",
    title: "Download in 4K",
    body: "Favorite the keepers and export upscaled, print-ready portraits.",
  },
];

const faqs = [
  {
    q: "How many photos do I need?",
    a: "A minimum of 10, but 15–25 varied selfies give the best identity match.",
  },
  {
    q: "How long does it take?",
    a: "Training and generation typically complete in about 30 minutes.",
  },
  {
    q: "Are my photos private?",
    a: "Your identity model is yours alone and never used to train shared models.",
  },
  {
    q: "What resolution do I get?",
    a: "Every delivered headshot is upscaled to 2K, with optional 4K on paid plans.",
  },
];

export default function Home() {
  return (
    <div className="flex min-h-full flex-col">
      <SiteNav />

      <main className="flex-1">
        {/* ───────────── Hero ───────────── */}
        <section className="relative mx-auto max-w-7xl px-5 pb-12 pt-14 sm:px-8 sm:pt-20">
          <div className="grid items-end gap-10 lg:grid-cols-[1.15fr_0.85fr]">
            <div>
              <p className="kicker rise text-muted" style={{ animationDelay: "0ms" }}>
                AI Studio · Est. 2026
              </p>
              <h1
                className="display rise mt-5 text-[clamp(2.75rem,7vw,5.5rem)]"
                style={{ animationDelay: "80ms" }}
              >
                Studio headshots
                <br />
                without the{" "}
                <span className="relative whitespace-nowrap text-electric">
                  studio
                  <svg
                    className="absolute -bottom-2 left-0 w-full"
                    viewBox="0 0 200 12"
                    fill="none"
                    aria-hidden
                  >
                    <path
                      d="M2 9C40 3 160 3 198 9"
                      stroke="currentColor"
                      strokeWidth="3"
                      strokeLinecap="round"
                    />
                  </svg>
                </span>
                .
              </h1>
              <p
                className="rise mt-7 max-w-md text-lg leading-relaxed text-muted"
                style={{ animationDelay: "160ms" }}
              >
                Upload a few selfies and get a gallery of professional,
                identity-accurate portraits — generated by AI, ranked for
                quality, delivered in minutes.
              </p>
              <div
                className="rise mt-9 flex flex-wrap items-center gap-3"
                style={{ animationDelay: "240ms" }}
              >
                <Link
                  href="/signup"
                  className="rounded-full bg-ink px-6 py-3.5 text-sm font-semibold text-paper transition-colors hover:bg-ink-raised"
                >
                  Create my headshots
                </Link>
                <a
                  href="#how"
                  className="rounded-full border border-line-strong px-6 py-3.5 text-sm font-semibold text-ink transition-colors hover:bg-ink/5"
                >
                  See how it works
                </a>
              </div>
              <p
                className="kicker rise mt-8 text-faint"
                style={{ animationDelay: "320ms" }}
              >
                ★★★★★ Loved by 10,000+ professionals
              </p>
            </div>

            {/* portrait cluster */}
            <div
              className="rise grid grid-cols-3 gap-3"
              style={{ animationDelay: "200ms" }}
            >
              <div className="col-span-2 space-y-3">
                <Portrait
                  seed={7}
                  label="Corporate"
                  className="aspect-[4/5] rounded-card"
                />
                <div className="grid grid-cols-2 gap-3">
                  <Portrait seed={21} className="aspect-square rounded-card" />
                  <Portrait seed={3} className="aspect-square rounded-card" />
                </div>
              </div>
              <div className="space-y-3">
                <Portrait seed={14} className="aspect-[3/4] rounded-card" />
                <div className="rounded-card border border-line bg-paper-raised p-4">
                  <p className="text-3xl font-extrabold tracking-tight">98%</p>
                  <p className="kicker mt-1 text-muted">Identity match</p>
                </div>
                <Portrait seed={31} label="Tech" className="aspect-[3/4] rounded-card" />
              </div>
            </div>
          </div>
        </section>

        {/* ───────────── Trusted-by marquee ───────────── */}
        <section className="border-y border-line py-5">
          <div className="flex items-center gap-3 overflow-hidden">
            <span className="kicker shrink-0 px-5 text-faint sm:px-8">
              Trusted by teams at
            </span>
            <div className="flex w-max gap-12 whitespace-nowrap pr-12 animate-marquee">
              {[...Array(2)].flatMap((_, r) =>
                ["Northwind", "Lumen", "Vector", "Pier 9", "Helio", "Quanta", "Atlas", "Forge"].map(
                  (b) => (
                    <span
                      key={`${r}-${b}`}
                      className="text-xl font-bold tracking-tight text-ink/35"
                    >
                      {b}
                    </span>
                  ),
                ),
              )}
            </div>
          </div>
        </section>

        {/* ───────────── How it works ───────────── */}
        <section id="how" className="mx-auto max-w-7xl px-5 py-20 sm:px-8 sm:py-28">
          <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end">
            <h2 className="display max-w-xl text-4xl sm:text-5xl">
              Four steps from selfie to portfolio.
            </h2>
            <p className="kicker text-muted">The workflow</p>
          </div>

          <div className="mt-14 grid gap-px overflow-hidden rounded-card border border-line bg-line sm:grid-cols-2 lg:grid-cols-4">
            {steps.map((s) => (
              <div
                key={s.n}
                className="group flex flex-col bg-paper-raised p-7 transition-colors hover:bg-paper-sunken"
              >
                <span className="font-mono text-sm text-electric">{s.n}</span>
                <h3 className="mt-10 text-xl font-bold tracking-tight">{s.title}</h3>
                <p className="mt-3 text-sm leading-relaxed text-muted">{s.body}</p>
              </div>
            ))}
          </div>
        </section>

        {/* ───────────── Stats band ───────────── */}
        <section className="bg-ink text-paper">
          <div className="mx-auto grid max-w-7xl grid-cols-2 gap-px bg-line-invert lg:grid-cols-4">
            {stats.map((s) => (
              <div key={s.label} className="bg-ink px-6 py-14 sm:px-8">
                <p className="display text-5xl text-paper sm:text-6xl">{s.value}</p>
                <p className="kicker mt-3 text-muted-dark">{s.label}</p>
              </div>
            ))}
          </div>
        </section>

        {/* ───────────── Styles ───────────── */}
        <section id="styles" className="mx-auto max-w-7xl px-5 py-20 sm:px-8 sm:py-28">
          <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end">
            <div>
              <p className="kicker text-muted">120+ scenarios</p>
              <h2 className="display mt-4 max-w-xl text-4xl sm:text-5xl">
                A style for every
                <br />
                kind of professional.
              </h2>
            </div>
            <Link
              href="/dashboard/gallery"
              className="hidden rounded-full border border-line-strong px-5 py-3 text-sm font-semibold transition-colors hover:bg-ink/5 sm:block"
            >
              Browse the gallery →
            </Link>
          </div>

          <div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {styleCategories.map((c, i) => (
              <div
                key={c.category}
                className="group overflow-hidden rounded-card border border-line bg-paper-raised"
              >
                <Portrait
                  seed={i * 19 + 5}
                  className="aspect-[16/10] w-full"
                  label={c.category}
                />
                <div className="flex flex-wrap gap-2 p-5">
                  {c.styles.map((s) => (
                    <span
                      key={s}
                      className="rounded-full border border-line bg-paper px-3 py-1.5 text-xs font-medium text-ink/80"
                    >
                      {s}
                    </span>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* ───────────── Pricing ───────────── */}
        <section id="pricing" className="bg-paper-sunken">
          <div className="mx-auto max-w-7xl px-5 py-20 sm:px-8 sm:py-28">
            <div className="text-center">
              <p className="kicker text-muted">Pricing</p>
              <h2 className="display mx-auto mt-4 max-w-2xl text-4xl sm:text-5xl">
                Pay once. Generate as much as your pack allows.
              </h2>
            </div>

            <div className="mt-14 grid gap-5 lg:grid-cols-3">
              {packages.map((p) => (
                <div
                  key={p.id}
                  className={`flex flex-col rounded-card border p-7 ${
                    p.featured
                      ? "border-electric bg-ink text-paper shadow-[0_24px_60px_-30px_rgba(30,53,255,0.6)]"
                      : "border-line bg-paper-raised"
                  }`}
                >
                  <div className="flex items-center justify-between">
                    <h3 className="text-xl font-bold tracking-tight">{p.name}</h3>
                    {p.featured ? (
                      <span className="kicker rounded-full bg-electric px-3 py-1 text-white">
                        Popular
                      </span>
                    ) : null}
                  </div>
                  <p
                    className={`mt-2 text-sm ${
                      p.featured ? "text-muted-dark" : "text-muted"
                    }`}
                  >
                    {p.blurb}
                  </p>
                  <div className="mt-6 flex items-end gap-1">
                    <span className="display text-5xl">${p.price}</span>
                    <span
                      className={`mb-1 text-sm ${
                        p.featured ? "text-muted-dark" : "text-muted"
                      }`}
                    >
                      one-time
                    </span>
                  </div>

                  <ul className="mt-7 space-y-3 border-t border-line-invert pt-7 text-sm">
                    {p.features.map((f) => (
                      <li key={f} className="flex items-center gap-3">
                        <span
                          className={`grid h-4 w-4 place-items-center rounded-full text-[10px] ${
                            p.featured ? "bg-electric text-white" : "bg-ink text-paper"
                          }`}
                        >
                          ✓
                        </span>
                        {f}
                      </li>
                    ))}
                  </ul>

                  <Link
                    href="/signup"
                    className={`mt-8 rounded-full px-5 py-3 text-center text-sm font-semibold transition-colors ${
                      p.featured
                        ? "bg-electric text-white hover:bg-electric-bright"
                        : "bg-ink text-paper hover:bg-ink-raised"
                    }`}
                  >
                    Choose {p.name}
                  </Link>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* ───────────── FAQ ───────────── */}
        <section id="faq" className="mx-auto max-w-7xl px-5 py-20 sm:px-8 sm:py-28">
          <div className="grid gap-12 lg:grid-cols-[0.8fr_1.2fr]">
            <h2 className="display text-4xl sm:text-5xl">
              Questions,
              <br />
              answered.
            </h2>
            <div className="divide-y divide-line border-y border-line">
              {faqs.map((f) => (
                <details key={f.q} className="group py-5">
                  <summary className="flex cursor-pointer list-none items-center justify-between text-lg font-semibold">
                    {f.q}
                    <span className="ml-4 text-2xl text-electric transition-transform group-open:rotate-45">
                      +
                    </span>
                  </summary>
                  <p className="mt-3 max-w-xl text-muted">{f.a}</p>
                </details>
              ))}
            </div>
          </div>
        </section>
      </main>

      <SiteFooter />
    </div>
  );
}
